# Generated by Django 3.2.12 on 2022-04-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0002_default_age"),
        ("authnapp", "0002_user_model_extend"),
    ]

    operations = []
